import type { RoleAssignment, Story } from "../types";

const personNames = { daughter: "女儿", parent1: "家长 1", parent2: "家长 2" } as const;
const cueStopWords = new Set(["a", "an", "and", "are", "can", "do", "here", "how", "i", "is", "it", "our", "the", "this", "to", "we", "will", "you", "your"]);

function cueWords(line: string) {
  return line.toLowerCase().match(/[a-z']+/g)?.filter((word) => !cueStopWords.has(word)).slice(0, 3).join(" · ") ?? "自己写关键词";
}

function puzzleWords(sentence: string) {
  return sentence.replace(/[.!?]/g, "").split(" ").reverse();
}

export function LearningPackPrint({ story, assignments }: { story: Story; assignments: RoleAssignment[] }) {
  const daughterRoles = assignments.find(({ personId }) => personId === "daughter")?.roleIds ?? [];
  const daughterLines = story.lines.filter(({ roleId }) => daughterRoles.includes(roleId));
  const reviewWords = story.learningPack.reviewWords;
  const scriptPages = [story.lines.slice(0, 6), story.lines.slice(6, 12), story.lines.slice(12, 18)];
  const wordCardPages = [story.learningPack.words.slice(0, 4), story.learningPack.words.slice(4)];
  const pages = [
    <section key="mission"><h1>{story.title}</h1><h2>1 · 家庭任务卡</h2><p className="micro-session-plan"><strong>每次 8–10 分钟</strong>：A 词汇 + 女儿台词 → 短休息 → B 分场排练 → 短休息 → C 全家演出 + 复习。可同晚分段，也可分两天完成。</p><ul>{story.roles.map((role) => { const owner = assignments.find((item) => item.roleIds.includes(role.id)); return <li key={role.id}>{role.emoji} {role.name} — {owner ? personNames[owner.personId] : "待分配"}</li>; })}</ul><h2>本课学习目标</h2><div className="mission-goals">{story.learningPack.patterns.map((pattern) => <div className="mission-goal" key={pattern.title}><strong>{pattern.title}</strong><span>{pattern.purpose}</span></div>)}</div><h2>7 天家庭学习路线</h2><div className="week-path"><div className="week-path-step"><strong>第 0 天 · 首演</strong><span>A 热身开口　B 分场排练　C 全家演出</span><em>日期：____　□ 完成</em></div><div className="week-path-step"><strong>第 2 天 · 唤醒</strong><span>抽红黄卡 → 说 2 个句型 → 重演一场</span><em>日期：____　□ 完成</em></div><div className="week-path-step"><strong>第 7 天 · 迁移</strong><span>旧词 + 新词造句 → 不看稿演出</span><em>日期：____　□ 完成</em></div></div><p className="family-promise">家庭约定：先让孩子完整说完，再提示；每天短练，不一次练太久。　家长签名：____________</p></section>,
    <section key="warmup"><h2>2 · 演前词汇热身</h2><p>由孩子自己勾选：</p>{story.learningPack.words.map((item) => <div className="mastery-row" key={item.word}><strong>{item.word}</strong><small className="word-type">{item.partOfSpeech}</small><span>{item.meaning}</span><span>□ 我认识　△ 有点难　○ 我不会</span></div>)}<div className="memory-toolbox"><h3>我的记词工具箱</h3><p>遇到难词，我自己选一种：□ 画小图　□ 拆成两段　□ 做动作　□ 编奇怪联想　□ 放进句子</p><p><strong>本次我主动选的 3 个难词：</strong> 1. __________　2. __________　3. __________</p></div><h3>我的生词救援站</h3><p>读剧本时遇到表外生词：先圈出来，结合上下文猜，再查证，最后用自己的句子说一次。</p><table className="unknown-word-journal"><thead><tr><th>生词</th><th>先猜意思</th><th>查证后</th><th>我自己的句子</th><th>第 2 天能说</th></tr></thead><tbody>{Array.from({ length: 4 }, (_, index) => <tr key={index}><td>________</td><td>________</td><td>________</td><td>________________</td><td>□</td></tr>)}</tbody></table></section>,
    ...scriptPages.map((lines, pageIndex) => <section className="pack-script-scene" key={`script-${pageIndex}`}><h2>3{String.fromCharCode(65 + pageIndex)} · 彩色完整剧本 · Scene {pageIndex + 1}</h2><p className="scene-rehearsal-note">本场 6 句：先慢读，再连续演；完成后用一句中文说说本场发生了什么。</p>{lines.map((line, index) => { const role = story.roles.find(({ id }) => id === line.roleId)!; return <div className={`pack-script-line role-color-${story.roles.indexOf(role) + 1}`} key={index}><strong>{role.emoji} {role.name}</strong>{line.stageDirection ? <em className="pack-direction">动作：{line.stageDirection}</em> : null}<p>{line.english}</p><small>{line.chinese}</small></div>})}<div className="scene-check"><strong>本场小检查</strong><p>用一句中文总结本场：________________________________________________</p><p>本场重点词：{Array.from(new Set(lines.flatMap(({ vocabulary = [] }) => vocabulary))).join(" · ") || "自己圈出 2 个词"}</p><p>□ 每句慢读　□ 6 句连续演　□ 盖住中文连续演　□ 换一个角色再演</p></div></section>),
    <section key="daughter"><h2>4 · 女儿角色练习页</h2><div className="fluency-guide"><h3>三遍开口阶梯</h3><p>说错不用怕：<strong>停一下 → 从句首重说 → 继续演</strong>。家长先不打断，整句说完再给一个提示。</p><p className="expression-marks"><strong>台词表达标记：</strong>○ 圈出重读词　/ 用 / 划分意群　↑ 问句末尾画 ↑　↓ 陈述句结尾画 ↓</p></div>{daughterLines.map((line, index) => <div className="daughter-line" key={index}><p>{line.english}</p><small>{line.pronunciation ?? "先慢读，再带着表情说一遍。"}{line.stageDirection ? <span className="daughter-action">　🎭 动作：{line.stageDirection}</span> : null}</small><div className="fluency-rounds"><span className="fluency-round">□ 第 1 遍 · 看完整台词</span><span className="fluency-round">□ 第 2 遍 · 只看关键词：{cueWords(line.english)}</span><span className="fluency-round">□ 第 3 遍 · 不看台词</span></div></div>)}</section>,
    <section key="patterns"><h2>5 · 句型与语法发现</h2><p className="transfer-rule"><strong>说 → 换 → 写 → 再说</strong>：先读故事原句，只替换一个部分，最后合上提示说自己的句子。</p>{story.learningPack.patterns.map((pattern) => <div className="pattern-box" key={pattern.title}><h3>{pattern.title}</h3><p>{pattern.purpose}</p><strong>{pattern.example}</strong><p className="pattern-template">{pattern.template}</p><p>替换词：{pattern.substitutions.join(" · ")}</p><p>小提醒：{pattern.grammarTip}</p>{pattern.tasks.map((task) => <p key={task}>□ {task}</p>)}<div className="pattern-transfer"><span>我的新句子：</span><span className="writing-line">________________________________________________</span></div><p className="pattern-self-check">□ 保留了句型骨架　□ 动作词形式正确　□ 不看纸说了一遍</p></div>)}</section>,
    <section key="puzzles"><h2>5B · 可剪句子拼图</h2><p className="puzzle-guide">沿虚线剪下词卡，打乱后<strong>拼回故事原句</strong>。读对后，<strong>换掉一张词卡</strong>，把新句子说给家人听。</p>{story.learningPack.patterns.map((pattern, patternIndex) => <div className="sentence-puzzle" key={pattern.title}><h3>拼图 {patternIndex + 1} · {pattern.title}</h3><div className="word-tiles">{puzzleWords(pattern.example).map((word, wordIndex) => <span className="word-tile" key={`${word}-${wordIndex}`}>{word}</span>)}</div><p>我拼的原句：________________________________________________________</p><p>换一张卡后的新句：__________________________________________________</p><p>□ 句首大写　□ 词序正确　□ 句末有标点　□ 大声说了一遍</p></div>)}</section>,
    <section key="detective"><h2>5C · 语法小侦探</h2><p className="detective-guide">每个案件都有一个语法错误。先圈出错误，再写出正确句子；答案在最后一页，由家长保管。</p>{story.learningPack.patterns.map((pattern, index) => <div className="grammar-detective-case" key={pattern.title}><h3>案件 {index + 1} · {pattern.title}</h3><p className="mistake-sentence">🕵️ {pattern.commonMistake}</p><p>我圈出的错误：________________　为什么：________________________________</p><p>正确句子：____________________________________________________________</p><p>□ 动作词形式　□ be 动词　□ 词序　□ 介词　□ 句末标点</p></div>)}<div className="detective-verdict"><strong>侦探结论</strong><p>我最容易犯的错误是：________________　下次说句子前我要检查：________________</p></div></section>,
    <section key="speaking"><h2>6 · 开口挑战</h2>{story.learningPack.speakingChallenges.map((challenge, index) => <div className="speaking-task" key={challenge.prompt}><strong>挑战 {index + 1}</strong><p>{challenge.prompt}</p><small>需要时才看提示：{challenge.hint}</small><p>家长签名：____________　完成：☆ ☆ ☆</p></div>)}<div className="performance-feedback"><h3>先演完，再反馈</h3><p>演出中不逐词纠正。结束后用<strong>两颗星 + 一个愿望</strong>：先说两个做得好的地方，再选一个下次目标。</p><div className="performance-feedback-grid"><div className="performance-feedback-column"><strong>孩子自评</strong><p>□ 声音够响　□ 句子完整</p><p>□ 有表情动作　□ 说错能重来</p><p>我最满意：________________</p></div><div className="performance-feedback-column"><strong>家长观察</strong><p>⭐ 做得好：________________</p><p>⭐ 做得好：________________</p><p>🌱 下次试试：______________</p></div></div></div></section>,
    <section key="retell"><h2>6B · 故事复述地图</h2><p className="retell-guide">先看关键词练习，再把纸盖住，用 <strong>First → Then → Finally</strong> 把故事讲给家人听。</p><div className="retell-map"><div className="retell-stage"><strong>1 · Who & Where</strong><span>提示：{story.learningPack.retell.settingHint}</span><p>我的开头：____________________________________________</p></div><div className="retell-stage"><strong>2 · Problem</strong><span>提示：{story.learningPack.retell.problemHint}</span><p>发生了什么：__________________________________________</p></div><div className="retell-stage"><strong>3 · Actions</strong><span>提示：{story.learningPack.retell.actionHints.join(" · ")}</span><p>First, __________________　Then, __________________</p></div><div className="retell-stage"><strong>4 · Ending</strong><span>提示：{story.learningPack.retell.endingHint}</span><p>Finally, ______________________________________________</p></div></div><div className="retell-finish"><strong>不看剧本讲 30–60 秒</strong><p>□ 用了 First / Then / Finally　□ 至少用了 3 个本课词　□ 说错能自己重来</p><p>第 1 次：____ 秒　　第 2 次：____ 秒　　我进步的地方：________________________</p></div></section>,
    <section key="conversation"><h2>6C · 家庭英语聊天卡</h2><p className="conversation-guide"><strong>先回答自己真实的想法</strong>，不需要和故事答案一样。第一次可以看开头，第二次盖住提示再说。</p>{story.learningPack.conversationPrompts.map((prompt, index) => <article className="conversation-card" key={prompt.question}><div className="conversation-number">{index + 1}</div><div><h3>{prompt.question}</h3><p>{prompt.chinese}</p><p className="answer-starter">开头提示：{prompt.starter}</p><p>我的第 1 次回答：____________________________________________________</p><p>加一个理由或细节：__________________________________________________</p><p>□ 完整句　□ 用了本课词　□ 说了 because / and　□ 不看提示又说一次</p></div></article>)}</section>,
    ...wordCardPages.map((words, pageIndex) => <section key={`cards-${pageIndex}`}><h2>7{pageIndex === 0 ? "A" : "B"} · 可折叠记忆卡</h2><p className="card-instructions">沿外框剪下，沿中线折叠。复习时遮住背面：<strong>先回答，再沿中线翻卡</strong>。</p><div className="memory-card-grid">{words.map((item) => <article className="memory-card word-memory-card" key={item.word}><div className="card-front"><small>正面 · 看英文回想意思</small><strong>{item.word}</strong><span className="word-type">{item.partOfSpeech}</span><span className="word-pronunciation">拆读：{item.pronunciation}</span><span>我能用它说一句话吗？</span></div><div className="card-fold-line">折叠线</div><div className="card-back"><small>背面 · 回答后再看</small><strong>{item.meaning}</strong><span>{item.example}</span><span className="memory-hook">我的记忆钩子：________</span></div></article>)}{pageIndex === 0 ? Array.from({ length: 2 }, (_, index) => <article className="memory-card blank-memory-card" key={index}><div className="card-front"><small>正面 · 自制生词卡</small><strong>我遇到的新词：________</strong><span>词性：______　拆读：________</span></div><div className="card-fold-line">折叠线</div><div className="card-back"><small>背面 · 自己补完整</small><span>意思：________________</span><span>我的句子：____________</span><span>记忆钩子：____________</span></div></article>) : null}{pageIndex === 1 ? story.learningPack.patterns.map((pattern) => <article className="memory-card sentence-card" key={pattern.title}><div className="card-front"><small>正面 · 补完整句</small><strong>{pattern.template}</strong></div><div className="card-fold-line">折叠线</div><div className="card-back"><small>背面 · 参考答案</small><strong>{pattern.example}</strong><span>{pattern.purpose}</span></div></article>) : null}</div>{pageIndex === 1 ? <div className="card-box-labels"><span className="box-red">○ 我不会盒</span><span className="box-yellow">△ 练习中盒</span><span className="box-green">□ 已掌握盒</span></div> : null}</section>),
    <section key="passport"><h2>8 · 我的复习护照</h2><p>每次只复习“有点难”和“我不会”的卡片。自己完成后画一颗星。</p><table className="review-passport"><thead><tr><th>时间</th><th>看中文说英文</th><th>放进句子</th><th>不开提示造句</th><th>我的星星</th></tr></thead><tbody><tr><th>演出当天</th><td>□</td><td>□</td><td>□</td><td>☆ ☆ ☆</td></tr><tr><th>第二天</th><td>□</td><td>□</td><td>□</td><td>☆ ☆ ☆</td></tr><tr><th>第七天</th><td>□</td><td>□</td><td>□</td><td>☆ ☆ ☆</td></tr></tbody></table><h3>卡片搬家</h3><p>红色“我不会”盒 → 黄色“练习中”盒 → 绿色“已掌握”盒</p><h3>看 → 盖 → 写 → 查</h3><p>只练我自己选的难词：先看清并读一遍，盖住原词，默写，再翻卡检查并圈出错的字母。</p><table className="spelling-practice"><thead><tr><th>难词</th><th>第 1 次默写</th><th>检查</th><th>第 2 次默写</th><th>我会了</th></tr></thead><tbody>{Array.from({ length: 4 }, (_, index) => <tr key={index}><td>________</td><td>____________</td><td>□ 圈错字母</td><td>____________</td><td>□</td></tr>)}</tbody></table><div className="voice-comparison"><strong>声音成长对比（可选）</strong><span>只保存在家长手机，不上传。</span><p>第 0 天录音：____ 秒　　第 7 天录音：____ 秒</p><p>我听见自己：□ 停顿更少　□ 句子更完整　□ 声音更清楚　□ 更有表情</p></div><p>本周我最想记住的句子：________________________________________</p></section>,
    <section key="rolling"><h2>9 · 旧词滚动挑战</h2><p className="rolling-rule">先完成本故事，再<strong>间隔 10 分钟后</strong>回来做。不要先翻词卡。</p>{reviewWords.map((item, index) => <div className="rolling-review-word" key={item.word}><strong>{index + 1}. {item.meaning} → ____________________</strong><span className="review-source">来自《{item.sourceStory}》</span><span>首字母：{item.word[0].toUpperCase()}　□ 独立想起　□ 看首字母想起　□ 重学</span><p>用这个词说一个<strong>不同于旧故事</strong>的新句子：________________________________</p></div>)}<div className="mixed-sentence"><h3>旧词 + 新词</h3><p>从上面选 1 个旧词，再从第 2 页选 1 个新词，把它们放进同一句话。</p><p>我的句子：________________________________________________________</p><p>□ 句子有主语　□ 动词形式正确　□ 我能大声说出来</p></div></section>,
    <section key="parent"><h2>10 · 家长抽查页</h2><p className="parent-only">家长保管</p><div className="evidence-key"><strong>记录方法：</strong> I = 独立说出　 H = 给提示后说出　 A = 看答案后重说</div>{story.learningPack.parentPrompts.map((prompt, index) => <p key={prompt}>{index + 1}. {prompt}</p>)}<table className="parent-evidence"><thead><tr><th>复习时间</th><th>8 个词<br />I / H / A</th><th>2 个句型<br />I / H / A</th><th>自己造句</th><th>能否自我纠错</th></tr></thead><tbody><tr><th>当天基线</th><td>__ / __ / __</td><td>__ / __ / __</td><td>□</td><td>□</td></tr><tr><th>第二天</th><td>__ / __ / __</td><td>__ / __ / __</td><td>□</td><td>□</td></tr><tr><th>第七天</th><td>__ / __ / __</td><td>__ / __ / __</td><td>□</td><td>□</td></tr></tbody></table><h3>纠错顺序</h3><p>等待 5 秒 → 只给首字母或动作提示 → 仍不会才给答案 → 请孩子合上答案完整重说。</p><h3>句子拼图答案</h3><p>{story.learningPack.patterns.map((pattern, index) => `${index + 1}. ${pattern.example}`).join("　")}</p><h3>语法侦探答案</h3>{story.learningPack.patterns.map((pattern, index) => <p key={pattern.title}>{index + 1}. <s>{pattern.commonMistake}</s> → <strong>{pattern.correction}</strong></p>)}<h3>答案与复习</h3><p>重点词：{story.learningPack.words.map(({ word, meaning }) => `${word}（${meaning}）`).join("；")}</p><p>□ 第二天抽查黄色和红色卡　□ 一周后再次造句　□ 会了的卡放入“已掌握”盒</p></section>,
  ];
  return <article className="learning-pack-print" aria-label="彩色故事学习包">{pages.map((page, index) => <div className="learning-pack-page" key={index}>{page}<footer>{story.title} · {index + 1} / {pages.length}</footer></div>)}</article>;
}
