import type { RoleAssignment, Story } from "../types";

const personNames = { daughter: "女儿", parent1: "家长 1", parent2: "家长 2" } as const;
const cueStopWords = new Set(["a", "an", "and", "are", "can", "do", "here", "how", "i", "is", "it", "our", "the", "this", "to", "we", "will", "you", "your"]);

function cueWords(line: string) {
  return line.toLowerCase().match(/[a-z']+/g)?.filter((word) => !cueStopWords.has(word)).slice(0, 3).join(" · ") ?? "自己写关键词";
}

export function LearningPackPrint({ story, assignments }: { story: Story; assignments: RoleAssignment[] }) {
  const daughterRoles = assignments.find(({ personId }) => personId === "daughter")?.roleIds ?? [];
  const daughterLines = story.lines.filter(({ roleId }) => daughterRoles.includes(roleId));
  const reviewWords = story.learningPack.words.filter(({ review }) => review);
  const pages = [
    <section key="mission"><h1>{story.title}</h1><h2>1 · 家庭任务卡</h2><p>25–30 分钟：词汇热身 5 分钟 · 排练 10 分钟 · 演出 8 分钟 · 复习 5 分钟</p><ul>{story.roles.map((role) => { const owner = assignments.find((item) => item.roleIds.includes(role.id)); return <li key={role.id}>{role.emoji} {role.name} — {owner ? personNames[owner.personId] : "待分配"}</li>; })}</ul></section>,
    <section key="warmup"><h2>2 · 演前词汇热身</h2><p>由孩子自己勾选：</p>{story.learningPack.words.map((item) => <div className="mastery-row" key={item.word}><strong>{item.word}</strong><span>{item.meaning}</span><span>□ 我认识　△ 有点难　○ 我不会</span>{item.review ? <small>滚动复习</small> : null}</div>)}</section>,
    <section key="script"><h2>3 · 彩色完整剧本</h2>{story.lines.map((line, index) => { const role = story.roles.find(({ id }) => id === line.roleId)!; return <div className={`pack-script-line role-color-${story.roles.indexOf(role) + 1}`} key={index}><strong>{role.emoji} {role.name}</strong><p>{line.english}</p><small>{line.chinese}</small></div>})}</section>,
    <section key="daughter"><h2>4 · 女儿角色练习页</h2><div className="fluency-guide"><h3>三遍开口阶梯</h3><p>说错不用怕：<strong>停一下 → 从句首重说 → 继续演</strong>。家长先不打断，整句说完再给一个提示。</p></div>{daughterLines.map((line, index) => <div className="daughter-line" key={index}><p>{line.english}</p><small>{line.pronunciation ?? "先慢读，再带着表情说一遍。"}</small><div className="fluency-rounds"><span className="fluency-round">□ 第 1 遍 · 看完整台词</span><span className="fluency-round">□ 第 2 遍 · 只看关键词：{cueWords(line.english)}</span><span className="fluency-round">□ 第 3 遍 · 不看台词</span></div></div>)}</section>,
    <section key="patterns"><h2>5 · 句型与语法发现</h2>{story.learningPack.patterns.map((pattern) => <div className="pattern-box" key={pattern.title}><h3>{pattern.title}</h3><p>{pattern.purpose}</p><strong>{pattern.example}</strong><p className="pattern-template">{pattern.template}</p><p>替换词：{pattern.substitutions.join(" · ")}</p><p>小提醒：{pattern.grammarTip}</p>{pattern.tasks.map((task) => <p key={task}>□ {task}</p>)}</div>)}</section>,
    <section key="speaking"><h2>6 · 开口挑战</h2>{story.learningPack.speakingChallenges.map((challenge, index) => <div className="speaking-task" key={challenge.prompt}><strong>挑战 {index + 1}</strong><p>{challenge.prompt}</p><small>需要时才看提示：{challenge.hint}</small><p>家长签名：____________　完成：☆ ☆ ☆</p></div>)}</section>,
    <section key="cards"><h2>7 · 可折叠记忆卡</h2><p className="card-instructions">沿外框剪下，沿中线折叠。复习时遮住背面：<strong>先回答，再沿中线翻卡</strong>。</p><div className="memory-card-grid">{story.learningPack.words.map((item) => <article className="memory-card word-memory-card" key={item.word}><div className="card-front"><small>正面 · 看英文回想意思</small><strong>{item.word}</strong><span className="word-pronunciation">拆读：{item.pronunciation}</span><span>我能用它说一句话吗？</span></div><div className="card-fold-line">折叠线</div><div className="card-back"><small>背面 · 回答后再看</small><strong>{item.meaning}</strong><span>{item.example}</span></div></article>)}{story.learningPack.patterns.map((pattern) => <article className="memory-card sentence-card" key={pattern.title}><div className="card-front"><small>正面 · 补完整句</small><strong>{pattern.template}</strong></div><div className="card-fold-line">折叠线</div><div className="card-back"><small>背面 · 参考答案</small><strong>{pattern.example}</strong><span>{pattern.purpose}</span></div></article>)}</div><div className="card-box-labels"><span className="box-red">○ 我不会盒</span><span className="box-yellow">△ 练习中盒</span><span className="box-green">□ 已掌握盒</span></div></section>,
    <section key="passport"><h2>8 · 我的复习护照</h2><p>每次只复习“有点难”和“我不会”的卡片。自己完成后画一颗星。</p><table className="review-passport"><thead><tr><th>时间</th><th>看中文说英文</th><th>放进句子</th><th>不开提示造句</th><th>我的星星</th></tr></thead><tbody><tr><th>演出当天</th><td>□</td><td>□</td><td>□</td><td>☆ ☆ ☆</td></tr><tr><th>第二天</th><td>□</td><td>□</td><td>□</td><td>☆ ☆ ☆</td></tr><tr><th>第七天</th><td>□</td><td>□</td><td>□</td><td>☆ ☆ ☆</td></tr></tbody></table><h3>卡片搬家</h3><p>红色“我不会”盒 → 黄色“练习中”盒 → 绿色“已掌握”盒</p><p>本周我最想记住的句子：________________________________________</p></section>,
    <section key="rolling"><h2>9 · 旧词滚动挑战</h2><p className="rolling-rule">先完成本故事，再<strong>间隔 10 分钟后</strong>回来做。不要先翻词卡。</p>{reviewWords.map((item, index) => <div className="rolling-review-word" key={item.word}><strong>{index + 1}. {item.meaning} → ____________________</strong><span>首字母：{item.word[0].toUpperCase()}　□ 独立想起　□ 看首字母想起　□ 重学</span><p>用这个词说一个<strong>不同于旧故事</strong>的新句子：________________________________</p></div>)}<div className="mixed-sentence"><h3>旧词 + 新词</h3><p>从上面选 1 个旧词，再从第 2 页选 1 个新词，把它们放进同一句话。</p><p>我的句子：________________________________________________________</p><p>□ 句子有主语　□ 动词形式正确　□ 我能大声说出来</p></div></section>,
    <section key="parent"><h2>10 · 家长抽查页</h2><p className="parent-only">家长保管</p><div className="evidence-key"><strong>记录方法：</strong> I = 独立说出　 H = 给提示后说出　 A = 看答案后重说</div>{story.learningPack.parentPrompts.map((prompt, index) => <p key={prompt}>{index + 1}. {prompt}</p>)}<table className="parent-evidence"><thead><tr><th>复习时间</th><th>8 个词<br />I / H / A</th><th>2 个句型<br />I / H / A</th><th>自己造句</th><th>能否自我纠错</th></tr></thead><tbody><tr><th>当天基线</th><td>__ / __ / __</td><td>__ / __ / __</td><td>□</td><td>□</td></tr><tr><th>第二天</th><td>__ / __ / __</td><td>__ / __ / __</td><td>□</td><td>□</td></tr><tr><th>第七天</th><td>__ / __ / __</td><td>__ / __ / __</td><td>□</td><td>□</td></tr></tbody></table><h3>纠错顺序</h3><p>等待 5 秒 → 只给首字母或动作提示 → 仍不会才给答案 → 请孩子合上答案完整重说。</p><h3>答案与复习</h3><p>重点词：{story.learningPack.words.map(({ word, meaning }) => `${word}（${meaning}）`).join("；")}</p><p>□ 第二天抽查黄色和红色卡　□ 一周后再次造句　□ 会了的卡放入“已掌握”盒</p></section>,
  ];
  return <article className="learning-pack-print" aria-label="彩色故事学习包">{pages.map((page, index) => <div className="learning-pack-page" key={index}>{page}<footer>{story.title} · {index + 1} / {pages.length}</footer></div>)}</article>;
}
